version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.1
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm ci
      - run: npm run test
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
  test:
    jobs:
      - test
